### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.0.2".

### ISSUE THREAD

**Issue by user023456789** [rotdrop/nextcloud-app-files-archive#19]
Hello,
Not really an issue but much more a prerequisite verification issue, it seems that some dependencies could not be resolved. On Debian stable this composer version is not available for the moment.
By installing the files_archive package the whole Nextcloud instance is broken until 'php occ app:remove files_archive' execution.
Regards

**Comment by rotdrop** [comment]
Actually, I am not sure whether the beast still works with php 7.

Also, as Nextcloud comes with pre-installed  PHP packages in its 3rdparty/ directory there is always the danger that things break.

One way out would be have different releases for the different Nextcloud versions which address mismatching PHP dependencies in a per-nextcloud-version manner.

Can you please report about the Nextcloud and PHP versions you are actually using?

Thanks for reporting!

Claus

**Comment by rotdrop** [comment]
BTW, there is also this PPA

https://launchpad.net/~ondrej/+archive/ubuntu/php

from which you can install PHP versions which are less outdated than the ones installed by Debian (the PPA also supports Debian stable and oldstable).

**Comment by adegans** [comment]
This hit me too, when I was still on PHP7.4... Add better dependency checks please.

**Comment by rotdrop** [comment]
> This hit me too, when I was still on PHP7.4... Add better dependency checks please.

Thanks for reporting problems: but: this is not helpful "better dependency checks". What do you mean this phrase?

**Comment by rotdrop** [comment]
Actually, problem here is that info.xml claims to support 7.4. I have changed this now 8.0 which should render the app as not installable (at least not through the GUI) on PHP 7.4 system. 

The composer file is not so much the problem here but rather the code which presumably uses features that are not present PHP 7.4. As least I assume that this is the case. More could only be concluded by a look at your Nextcloud or web server logs.

I am closing this bug now as resolved per 3b370931aedc5a2484a8528a6bfba4f6b5e7fb79
