### ISSUE TITLE
NC26

### ISSUE THREAD

**Issue by Aonodensetsu** [rotdrop/nextcloud-app-files-archive#24]
Add support for Nextcloud version 26, please.

**Comment by rotdrop** [comment]
Hi, in order to support the support for NC26, could you please try whether the app in principle works? I think the administrator can enable unsupported apps, otherwise please just edit appinfo/info.xml. Thank you for your help!

Of course, eventually as time permits I will support NC26 in this and my other apps.

**Comment by Aonodensetsu** [comment]
My NC broke with the major update (caused by Passwords app) so I'm currently trying to get the NC team to fix that issue, will try to revisit when time permits.

**Comment by stmichalke** [comment]
NC 26.0.0.11 doesn't work with files_archive 1.1.3-rc1 enabled because:

"url":"/apps/files/","message":"Declaration of OCA\\FilesArchive\\Storage\\ArchiveStorage::filesize($path) must be compatible with OC\\Files\\Storage\\Common::filesize($path): int|float|false

**Comment by stmichalke** [comment]
The app works fine with « filesize($path): int|float|false » in files_archive/lib/Storage/ArchiveStorage.php 

I'd like to thank you for your app, BTW. It's very useful.

**Comment by stmichalke** [comment]
FYI, with commit 10ab6da02691343220c1fec3a47e5703ea4e1a9f applied the app works with NC27 too.

**Comment by rotdrop** [comment]
Should be solved by https://github.com/rotdrop/nextcloud-app-files-archive/releases/tag/v1.1.3
