### ISSUE TITLE
Nextcloud v28 support  [was: Error, PHP Deprecated]

### ISSUE THREAD

**Issue by teemue** [rotdrop/nextcloud-app-files-archive#30]
The following error occurred during  occ files:scan --all:

```
PHP Deprecated:  Return type of OCA\FilesArchive\Db\ArchiveMount::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/custom_apps/files_archive/lib/Db/ArchiveMount.php on line 93
```

NC 28.0.0
PHP: 8.2.13

**Comment by therealeldaria** [comment]
Archive Manager is not listed as having support for NC 28

**Comment by rotdrop** [comment]
Hi there,

it is unfortunately not as easy as just incrementing the version number in info.xml. However, I am currently working on porting several apps to NC 28, so this will be addressed sooner or later (depending on the time I can spend on hacking NC apps).

**Comment by rotdrop** [comment]
> The following error occurred during occ files:scan --all:
> 
> ```
> PHP Deprecated:  Return type of OCA\FilesArchive\Db\ArchiveMount::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/custom_apps/files_archive/lib/Db/ArchiveMount.php on line 93
> ```
> 
> NC 28.0.0 PHP: 8.2.13

Fixed in ec034fe

**Comment by rotdrop** [comment]
> Ok, [pdf_downloader](https://github.com/rotdrop/nextcloud-app-pdf-downloader) has more or less been ported to v28 and I am working on this one now. Things look good so far. Things work differently but in principle are easier to implement. In particular the file-list updates are easier to handle via the new NC event bus stuff.

Maybe the stuff now works properly with NC 28:
- use the event-bus in order to track and initiate front-end changes
- listen on notifications in order to update the frontend
- improve the use of the file-cache to make listings more efficient

The stable28 branch contains compiled assets. It may or may not work for you, but in principle it should be possible to just check it out with git. There will be a pre-release and maybe a release for NC 28 over the weekend. I can be that I just leave the code for NC 27 and 26 as is (but for issues reported).

**Comment by rotdrop** [comment]
Closing this with the release of v1.2.0
