### ISSUE TITLE
Error in logs while extracting archive: Unable to add style asset files-sidebar-hooks

### ISSUE THREAD

**Issue by Egor3f** [rotdrop/nextcloud-app-files-archive#37]
To reproduct this error:
1. Open archive file details
2. Select "extract archive" and check both checkboxes (background and strip prefix)
3. Press "extract archive"
4. You'll see no changes in file panel, one notification under "bell" menu in top bar, and the following message in error logs. Files are successfully extracted indeed

Error message:
```
Installation problem; the required resource "files-sidebar-hooks" of type "css" is not installed on the server, please contact the system administrator!
/var/www/html/custom_apps/files_archive/lib/Listener/FilesActionListener.php:179: OCA\FilesArchive\Listener\FilesActionListener::handle: Unable to add style asset files-sidebar-hooks
```

App version: 1.22

Nextcloud version info: [Nextcloud Hub 7](https://nc.efprojects.com/) (28.0.3)
PHP version info: 
```
Version: 8.2.17
Memory limit: 512 MB
Max execution time: 3600
Upload max size: 512 MB
OPcache Revalidate Frequency: 60
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, ftp, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache
```

**Comment by Egor3f** [comment]
Sorry, didn't see it was already submitted here https://github.com/rotdrop/nextcloud-app-files-archive/issues/36

**Comment by rotdrop** [comment]
Ok then, lets continue with this in #36 although you description is much clearer than the notes in #36.

**Comment by imforumman** [comment]
Ok, so I don't understand Issue 36 at all, I'm just seeing the same error:

EnduserNotificationException Installation problem; the required resource "files-sidebar-hooks" of type "css" is not installed on the server, please contact the system administrator! /volume1/web/nextcloud/apps/files_archive/lib/Listener/FilesActionListener.php:179: OCA\FilesArchive\Listener\FilesActionListener::handle: Unable to add style asset files-sidebar-hooks

appears in the Logs and I don't quite understand what this error is trying to tell me, as the Archive Manager seems to be working quite well (hence I gather your comment on 36 "do we have a real bug here?"). I just like it when things that have the potential to destroy all things in my cloud don't throw errors I don't understand: ;-)

This is using Version 1.2.2 in NC 28.0.4.

Can I do anything to provide more information or do I just need to wait for a new version to be released?
Thank you so much for this app, I'm hoping that the DICOM-Viewer will soon be able to use mounted archives, then this will be much more than I was hoping for when I was looking for an app to zip/unzip.

**Comment by rotdrop** [comment]
Please do not comment in closed issue. As pointed out in #36 the issue  already is fixed, there I even gave the hash of the commit which fixed it.
